In [25]:
import pandas as pd

filepath='C:\\Users\\Admin\\Downloads\\iplauction2023.csv'
# converting column 'name' into a index_column.
s = pd.read_csv(filepath, index_col='name')
s

,player_style,nationality,base price (in lacs),final price (in lacs),franchise,status
name,,,,,,
Harshit Rana,Bowler,India,NaN,20.0,KKR,RETAINED
Ekant Sen,Batter,India,20.0,NaN,NaN,UNSOLD
Wayne Parnell,Allrounder,South Africa,75.0,NaN,NaN,UNSOLD
Shakib Al Hasan,Allrounder,Bangladesh,150.0,150.0,KKR,SOLD
Joe Root,Batter,England,100.0,100.0,RR,SOLD
...,...,...,...,...,...,...
MS Dhoni,WK-Batter,India,NaN,1200.0,CSK,RETAINED
Moeen Ali,Allrounder,England,NaN,800.0,CSK,RETAINED
Ruturaj Gaikwad,Batter,India,NaN,600.0,CSK,RETAINED
Rishabh Pant,WK-Batter,India,NaN,1600.0,DC,RETAINED
Axar Patel,Allrounder,India,NaN,900.0,DC,RETAINED